# Generated by Django 3.0.5 on 2020-05-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectionapp', '0003_auto_20200501_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selectionapp.Coordinate'),
        ),
        migrations.AddField(
            model_name='point',
            name='enemies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selectionapp.Enemy'),
        ),
    ]
