# Generated by Django 3.0.5 on 2020-05-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectionapp', '0004_auto_20200501_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='point',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='point',
            name='enemies',
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
        migrations.DeleteModel(
            name='Enemy',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
